global using AutoMapper;
global using FluentValidation;
global using System.Linq;
global using System.Reflection;
global using Exp.Todo.Domain.Entities;
global using Exp.Todo.Application.Services;
global using Exp.Todo.Application.Dtos;
global using Exp.Todo.Application.Interfaces.Persistence;
global using Exp.Todo.Application.Common.Exceptions;
global using Microsoft.Extensions.DependencyInjection;
global using TodoEntity = Exp.Todo.Domain.Entities.Todo;
